name: CI

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master

jobs:
  all:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: --deny warnings
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust Toolchain Components
        uses: actions-rs/toolchain@v1
        with:
          components: clippy, rustfmt
          override: true
          toolchain: 1.58.1
      - uses: Swatinem/rust-cache@v1
        with:
          key: 0
      - name: Test
        run: cargo test
      - name: Clippy
        run: cargo clippy --tests
      - name: Check Formatting
        run: cargo fmt -- --check
